"""fix_column_types

Revision ID: 3e4ee41d6bcd
Revises: d3b1c0bc722a
Create Date: 2026-02-23 23:34:47.662143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4ee41d6bcd'
down_revision: Union[str, None] = 'd3b1c0bc722a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE login_history
        ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
        USING created_at::TIMESTAMP WITH TIME ZONE
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE login_history
        ALTER COLUMN created_at TYPE VARCHAR(50)
        USING created_at::VARCHAR
    """)
    # ### end Alembic commands ###
